In [2]:
import torch

In [4]:
eigenvalues = torch.tensor([4, 2, 1, 3, 5, 10])
eigenvectors = torch.randn(5, 6)

eigenvalues, eigenvectors


(tensor([ 4,  2,  1,  3,  5, 10]),
 tensor([[ 0.4705, -1.0491, -0.3543,  0.6395, -0.9333,  0.0771],
         [ 0.3297, -1.5747, -0.8626,  1.9281, -0.1541, -1.0527],
         [ 1.1731, -1.1578, -0.2183, -0.0241,  0.7969, -1.0405],
         [ 0.3962,  0.1880, -0.6937,  1.2480, -1.7121, -0.4411],
         [ 0.5339, -0.0099,  1.3139,  0.2973, -0.1258,  0.5217]]))

In [5]:
idx = torch.argsort(eigenvalues, descending = True)
idx

tensor([5, 4, 0, 3, 1, 2])

In [6]:
new_eigenvals = eigenvalues[idx]
new_eigenvals

tensor([10,  5,  4,  3,  2,  1])

In [7]:
new_eigenvecs = eigenvectors[:, idx]
new_eigenvecs

tensor([[ 0.0771, -0.9333,  0.4705,  0.6395, -1.0491, -0.3543],
        [-1.0527, -0.1541,  0.3297,  1.9281, -1.5747, -0.8626],
        [-1.0405,  0.7969,  1.1731, -0.0241, -1.1578, -0.2183],
        [-0.4411, -1.7121,  0.3962,  1.2480,  0.1880, -0.6937],
        [ 0.5217, -0.1258,  0.5339,  0.2973, -0.0099,  1.3139]])

In [1]:
import torch
from svd import svd as solver

In [2]:
A = torch.rand(5, 10)

In [5]:
svd = solver.SVD(tolerance=1e-4, max_iterations=100000, seed=24)

svd.fit(A)
A_hat = svd.reconstruct()

print(torch.norm(A-A_hat))

tensor(0.0004)


In [6]:
A, A_hat

(tensor([[0.3073, 0.7116, 0.8892, 0.7881, 0.3010, 0.1315, 0.0700, 0.7399, 0.7503,
          0.0666],
         [0.4332, 0.0329, 0.0502, 0.2715, 0.3262, 0.2102, 0.8835, 0.6940, 0.8607,
          0.8239],
         [0.8591, 0.5588, 0.4641, 0.9196, 0.2178, 0.7390, 0.4700, 0.1714, 0.8488,
          0.9406],
         [0.6100, 0.6784, 0.9064, 0.7991, 0.0370, 0.0912, 0.9106, 0.1171, 0.8145,
          0.4951],
         [0.7448, 0.5994, 0.2263, 0.5107, 0.0748, 0.8484, 0.1137, 0.4558, 0.1894,
          0.3771]]),
 tensor([[0.3073, 0.7116, 0.8892, 0.7881, 0.3010, 0.1314, 0.0700, 0.7399, 0.7503,
          0.0666],
         [0.4333, 0.0329, 0.0502, 0.2715, 0.3262, 0.2102, 0.8835, 0.6940, 0.8606,
          0.8239],
         [0.8592, 0.5589, 0.4641, 0.9196, 0.2178, 0.7391, 0.4701, 0.1714, 0.8487,
          0.9406],
         [0.6101, 0.6785, 0.9064, 0.7990, 0.0369, 0.0912, 0.9106, 0.1171, 0.8143,
          0.4950],
         [0.7449, 0.5994, 0.2263, 0.5107, 0.0747, 0.8485, 0.1138, 0.4557, 0.1894,
       

In [5]:
print(svd.U.shape)
print(svd.Sigma.shape)
print(svd.V.shape)

torch.Size([5, 5])
torch.Size([5, 5])
torch.Size([10, 5])


In [5]:
I = svd.U.T @ svd.U

print(torch.linalg.norm(I - torch.eye(I.shape[0])))

tensor(0.0004)


In [6]:
I = svd.V.T @ svd.V

print(torch.linalg.norm(I - torch.eye(I.shape[0])))

tensor(0.0002)


In [7]:
for i in range(len(svd.singular_values)):
    lhs = A @ svd.V[:, i]
    rhs = svd.singular_values[i] * svd.U[:, i]

    print(torch.linalg.norm(lhs - rhs))

tensor(1.1921e-07)
tensor(0.)
tensor(0.)
tensor(1.4901e-08)
tensor(1.4901e-08)


In [8]:
U, S, Vh = torch.linalg.svd(A, full_matrices=False)

In [9]:
print(torch.linalg.norm(S - svd.singular_values))

tensor(9.1178e-07)
